# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Statistics Resources
tagline:          'Help for the confused'
description:      'Help for the statistically confused'
url:              https://hueywoonlee.github.io/
baseurl:          /

author:
  name:           'Huey Woon Lee'
  url:            ###

paginate:         5

# Custom vars
version:          ###

github:
  repo:           https://github.com/hueywoonlee/hueywoonlee.github.io

theme: jekyll-theme-slate
